holidays = [{"holiday": "Polar Bear Plunge Day", "day": "January 1"}, {"holiday": "Run It up the Flagpole and See If Anyone Salutes It Day", "day": "January 2"}, 
	{"holiday": "Science Fiction Day", "day": "January 2"}, {"holiday": "Festival of Sleep Day", "day": "January 3"}, {"holiday": "Fruitcake Toss Day", "day": "January 3"}, 
	{"holiday": "National Spaghetti Day", "day": "January 4"}, {"holiday": "Trivia Day", "day": "January 4"}, {"holiday": "Bird Day", "day": "January 5"}, 
	{"holiday": "Bean Day", "day": "January 6"}, {"holiday": "Old Rock Day", "day": "January 7"}, {"holiday": "Earth's Rotation Day", "day": "January 8"}, 
	{"holiday": "Static Electricity Day", "day": "January 9"}, {"holiday": "Word Nerd Day", "day": "January 9"}, {"holiday": "Clean Off Your Desk Day", "day": "January 9"}, 
	{"holiday": "Cut Your Energy Costs Day", "day": "January 10"}, {"holiday": "Learn Your Name in Morse Code Day", "day": "January 11"}, {"holiday": "Kiss A Ginger Day", "day": "January 12"}, 
	{"holiday": "Marzipan Day", "day": "January 12"}, {"holiday": "Make Your Dreams Come True Day", "day": "January 13"}, {"holiday": "Organize Your Home Day", "day": "January 14"}, 
	{"holiday": "National Hat Day", "day": "January 15"}, {"holiday": "Strawberry Ice Cream Day", "day": "January 15"}, {"holiday": "Blue Monday", "day": "January 16"}, 
	{"holiday": "Nothing Day", "day": "January 16"}, {"holiday": "Ditch New Year's Resolution Day", "day": "January 17"}, {"holiday": "Kid Inventors' Day", "day": "January 17"}, 
	{"holiday": "Benjamin Franklin Day", "day": "January 17"}, {"holiday": "Thesaurus Day", "day": "January 18"}, {"holiday": "Winnie The Pooh Day", "day": "January 18"}, 
	{"holiday": "Tin Can Day", "day": "January 19"}, {"holiday": "Popcorn Day", "day": "January 19"}, {"holiday": "Penguin Awareness Day", "day": "January 20"}, 
	{"holiday": "Squirrel Appreciation Day", "day": "January 21"}, {"holiday": "Soup Swap Day", "day": "January 21"}, {"holiday": "National Hug Day", "day": "January 21"}, 
	{"holiday": "Hot Sauce Day", "day": "January 22"}, {"holiday": "National Pie Day", "day": "January 23"}, {"holiday": "Handwriting Day", "day": "January 23"}, 
	{"holiday": "National Peanut Butter Day", "day": "January 24"}, {"holiday": "Macintosh Computer Day", "day": "January 24"}, {"holiday": "Compliment Day", "day": "January 24"}, 
	{"holiday": "Opposite Day", "day": "January 25"}, {"holiday": "National Spouses Day", "day": "January 26"}, {"holiday": "Spouse's Day", "day": "January 26"}, 
	{"holiday": "e-Day", "day": "January 27"}, {"holiday": "Chocolate Cake Day", "day": "January 27"}, {"holiday": "Data Privacy Day", "day": "January 28"}, 
	{"holiday": "Fun at Work Day", "day": "January 28"}, {"holiday": "Puzzle Day", "day": "January 29"}, {"holiday": "Croissant Day", "day": "January 30"}, {"holiday": "Backwards Day", "day": "January 31"}, 
	{"holiday": "Work Naked Day", "day": "February 1"}, {"holiday": "Play Your Ukulele Day", "day": "February 2"}, {"holiday": "Day of the Cr\u00eape", "day": "February 2"}, 
	{"holiday": "Carrot Cake Day", "day": "February 3"}, {"holiday": "Eat Ice Cream for Breakfast Day", "day": "February 4"}, {"holiday": "Stuffed Mushroom Day", "day": "February 4"}, 
	{"holiday": "Create a Vacuum Day", "day": "February 4"}, {"holiday": "Thank Your Mailman Day", "day": "February 4"}, {"holiday": "Chocolate Fondue Day", "day": "February 5"}, 
	{"holiday": "National Weatherperson's Day", "day": "February 5"}, {"holiday": "World Nutella Day", "day": "February 5"}, {"holiday": "Lame Duck Day", "day": "February 6"}, 
	{"holiday": "Safer Internet Day", "day": "February 7"}, {"holiday": "e-Day", "day": "February 7"}, {"holiday": "Send a Card to a Friend Day", "day": "February 7"}, 
	{"holiday": "Laugh and Get Rich Day", "day": "February 8"}, {"holiday": "National Bagel Day", "day": "February 9"}, {"holiday": "Toothache Day", "day": "February 9"}, 
	{"holiday": "National Pizza Day", "day": "February 9"}, {"holiday": "Umbrella Day", "day": "February 10"}, {"holiday": "Make a Friend Day", "day": "February 11"}, 
	{"holiday": "Don't Cry Over Spilled Milk Day", "day": "February 11"}, {"holiday": "Darwin Day", "day": "February 12"}, {"holiday": "Clean Out Your Computer Day", "day": "February 13"}, 
	{"holiday": "Ferris Wheel Day", "day": "February 14"}, {"holiday": "Library Lovers Day", "day": "February 14"}, {"holiday": "Singles Awareness Day", "day": "February 15"}, 
	{"holiday": "Gumdrop Day", "day": "February 15"}, {"holiday": "Do a Grouch a Favor Day", "day": "February 16"}, {"holiday": "Random Act of Kindness Day", "day": "February 17"}, 
	{"holiday": "Battery Day", "day": "February 18"}, {"holiday": "National Drink Wine Day", "day": "February 18"}, {"holiday": "Chocolate Mint Day", "day": "February 19"}, 
	{"holiday": "National Love Your Pet Day", "day": "February 20"}, {"holiday": "Hoodie Hoo Day", "day": "February 20"}, {"holiday": "Single Tasking Day", "day": "February 22"}, 
	{"holiday": "Be Humble Day", "day": "February 22"}, {"holiday": "National Margarita Day", "day": "February 22"}, {"holiday": "International Dog Biscuit Appreciation Day", "day": "February 23"}, 
	{"holiday": "National Chili Day", "day": "February 23"}, {"holiday": "Tortilla Chip Day", "day": "February 24"}, {"holiday": "World Sword Swallowers Day", "day": "February 25"}, 
	{"holiday": "Pistachio Day", "day": "February 26"}, {"holiday": "Tell a Fairy Tale Day", "day": "February 26"}, {"holiday": "No Brainer Day", "day": "February 27"}, 
	{"holiday": "Rare Disease Day", "day": "February 28"}, {"holiday": "Public Sleeping Day", "day": "February 28"}, {"holiday": "World Compliment Day", "day": "March 1"}, 
	{"holiday": "National Pig Day", "day": "March 1"}, {"holiday": "Plan a Solo Vacation Day", "day": "March 1"}, {"holiday": "Dr. Seuss Day", "day": "March 2"}, 
	{"holiday": "Old Stuff Day", "day": "March 2"}, {"holiday": "I Want You to be Happy Day", "day": "March 3"}, {"holiday": "March Forth and Do Something Day", "day": "March 4"}, 
	{"holiday": "Learn What Your Name Means Day", "day": "March 5"}, {"holiday": "Cinco de Marcho", "day": "March 5"}, {"holiday": "National Oreo Day", "day": "March 6"}, 
	{"holiday": "Dentist\u2019s Day", "day": "March 6"}, {"holiday": "Alexander Graham Bell Day", "day": "March 7"}, {"holiday": "National Cereal Day", "day": "March 7"}, 
	{"holiday": "Proofreading Day", "day": "March 8"}, {"holiday": "National Meatball Day", "day": "March 9"}, {"holiday": "Mario Day", "day": "March 10"}, 
	{"holiday": "Oatmeal Nut Waffle Day", "day": "March 11"}, {"holiday": "Alfred Hitchcock Day", "day": "March 12"}, {"holiday": "Jewel Day", "day": "March 13"}, 
	{"holiday": "Napping Day", "day": "March 13"}, {"holiday": "Pi Day", "day": "March 14"}, {"holiday": "Steak and BJ Day", "day": "March 14"}, 
	{"holiday": "Everything You Think is Wrong Day", "day": "March 15"}, {"holiday": "Ides of March", "day": "March 15"}, 
	{"holiday": "Absolutely Incredible Kid Day", "day": "March 16"}, {"holiday": "Every Thing You Do is Right Day", "day": "March 16"}, 
	{"holiday": "Submarine Day", "day": "March 17"}, {"holiday": "Awkward Moments Day", "day": "March 18"}, {"holiday": "Let's Laugh Day", "day": "March 19"}, 
	{"holiday": "World Storytelling Day", "day": "March 20"}, {"holiday": "Proposal Day", "day": "March 20"}, {"holiday": "Common Courtesy Day", "day": "March 21"}, 
	{"holiday": "National Goof Off Day", "day": "March 22"}, {"holiday": "Near Miss Day", "day": "March 23"}, {"holiday": "OK Day", "day": "March 23"}, 
	{"holiday": "Puppy Day", "day": "March 23"}, {"holiday": "Chocolate Covered Raisins Day", "day": "March 24"}, {"holiday": "Waffle Day", "day": "March 25"}, 
	{"holiday": "Tolkien Reading Day", "day": "March 25"}, {"holiday": "Make Up Your Own Holiday Day", "day": "March 26"}, {"holiday": "Purple Day", "day": "March 26"}, 
	{"holiday": "Spanish Paella Day", "day": "March 27"}, {"holiday": "Something on a Stick Day", "day": "March 28"}, {"holiday": "Smoke and Mirrors Day", "day": "March 29"}, 
	{"holiday": "Take a Walk in the Park Day", "day": "March 30"}, {"holiday": "National Doctors' Day", "day": "March 30"}, {"holiday": "Bunsen Burner Day", "day": "March 31"}, 
	{"holiday": "National Crayon Day", "day": "March 31"}, {"holiday": "World Party Day", "day": "April 3"}, {"holiday": "Tell a Lie Day", "day": "April 4"}, 
	{"holiday": "Read a Road Map Day", "day": "April 5"}, {"holiday": "First Contact Day", "day": "April 5"}, {"holiday": "Sorry Charlie Day", "day": "April 6"}, 
	{"holiday": "National Tartan Day", "day": "April 6"}, {"holiday": "National Beer Day", "day": "April 7"}, {"holiday": "Walk to Work Day", "day": "April 7"}, {"holiday": "Siblings Day", "day": "April 10"}, 
	{"holiday": "Barbershop Quartet Day", "day": "April 11"}, {"holiday": "Be Kind to Lawyers Day", "day": "April 11"}, {"holiday": "National Pet Day", "day": "April 11"}, 
	{"holiday": "Grilled Cheese Day", "day": "April 12"}, {"holiday": "Yuri's Night", "day": "April 12"}, {"holiday": "Scrabble Day", "day": "April 13"}, 
	{"holiday": "International Moment of Laughter Day", "day": "April 14"}, {"holiday": "Reach as High as You Can Day", "day": "April 14"}, {"holiday": "Look up the Sky Day", "day": "April 14"}, 
	{"holiday": "Record Store Day", "day": "April 15"}, {"holiday": "Eggs Benedict Day", "day": "April 16"}, {"holiday": "Wear Pajamas to Work Day", "day": "April 16"}, 
	{"holiday": "Herbalist Day", "day": "April 17"}, {"holiday": "Haiku Poetry Day", "day": "April 17"}, {"holiday": "Columnist Day", "day": "April 18"}, 
	{"holiday": "Bicycle Day", "day": "April 19"}, {"holiday": "Look Alike Day", "day": "April 20"}, {"holiday": "National High Five Day", "day": "April 20"}, 
	{"holiday": "Lima Bean Respect Day", "day": "April 20"}, {"holiday": "The Day of Silence", "day": "April 21"}, {"holiday": "Jelly Bean Day", "day": "April 22"}, 
	{"holiday": "Take a Chance Day", "day": "April 23"}, {"holiday": "Impossible Astronaut Day", "day": "April 23"}, {"holiday": "Lover's Day", "day": "April 23"}, 
	{"holiday": "Poem in Your Pocket Day", "day": "April 24"}, {"holiday": "DNA Day", "day": "April 25"}, {"holiday": "Pretzel Day", "day": "April 26"}, 
	{"holiday": "Richter Scale Day", "day": "April 26"}, {"holiday": "Take Our Daughters and Sons to Work Day", "day": "April 27"}, 
	{"holiday": "World Pinhole Photography Day", "day": "April 27"}, {"holiday": "Zipper Day", "day": "April 29"}, {"holiday": "International Dance Day", "day": "April 29"}, 
	{"holiday": "Astronomy Day", "day": "April 29"}, {"holiday": "Honesty Day", "day": "April 30"}, {"holiday": "Batman Day", "day": "May 1"}, {"holiday": "Star Wars Day", "day": "May 4"}, 
	{"holiday": "No Pants Day", "day": "May 5"}, {"holiday": "Space Day", "day": "May 5"}, {"holiday": "Herb Day", "day": "May 6"}, {"holiday": "World Naked Gardening Day", "day": "May 6"}, 
	{"holiday": "Free Comic Book Day", "day": "May 6"}, {"holiday": "Beverage Day", "day": "May 6"}, {"holiday": "International No Diet Day", "day": "May 6"}, 
	{"holiday": "Lost Sock Memorial Day", "day": "May 9"}, {"holiday": "Europe Day", "day": "May 9"}, {"holiday": "National School Nurse Day", "day": "May 10"}, 
	{"holiday": "Clean Up Your Room Day", "day": "May 10"}, {"holiday": "Twilight Zone Day", "day": "May 11"}, {"holiday": "Eat What You Want Day", "day": "May 11"}, 
	{"holiday": "Limerick Day", "day": "May 12"}, {"holiday": "Military Spouse Appreciation Day", "day": "May 12"}, {"holiday": "Frog Jumping Day", "day": "May 13"}, 
	{"holiday": "Dance Like a Chicken Day", "day": "May 14"}, {"holiday": "Chocolate Chip Day", "day": "May 15"}, {"holiday": "Pack Rat Day", "day": "May 17"}, 
	{"holiday": "No Dirty Dishes Day", "day": "May 18"}, {"holiday": "May Ray Day", "day": "May 19"}, {"holiday": "Pizza Party Day", "day": "May 19"}, 
	{"holiday": "Bike to Work Day", "day": "May 19"}, {"holiday": "Be a Millionaire Day", "day": "May 20"}, {"holiday": "Talk Like Yoda Day", "day": "May 21"}, 
	{"holiday": "Buy a Musical Instrument Day", "day": "May 22"}, {"holiday": "World Turtle Day", "day": "May 23"}, {"holiday": "Scavenger Hunt Day", "day": "May 24"}, 
	{"holiday": "Towel Day", "day": "May 25"}, {"holiday": "Sing Out Day", "day": "May 25"}, {"holiday": "National Wine Day", "day": "May 25"}, 
	{"holiday": "World Lindy Hop Day", "day": "May 26"}, {"holiday": "Sun Screen Day", "day": "May 27"}, {"holiday": "Hamburger Day", "day": "May 28"}, 
	{"holiday": "Put a Pillow on Your Fridge Day", "day": "May 29"}, {"holiday": "My Bucket's Got a Hole Day", "day": "May 30"}, 
	{"holiday": "Macaroon Day", "day": "May 31"}, {"holiday": "Say Something Nice Day", "day": "June 1"}, 
	{"holiday": "Leave the Office Early Day", "day": "June 2"}, {"holiday": "National Donut Day", "day": "June 2"}, 
	{"holiday": "Repeat Day", "day": "June 3"}, {"holiday": "National Cheese Day", "day": "June 4"}, {"holiday": "Hug Your Cat Day", "day": "June 4"}, 
	{"holiday": "Drive-In Movie Day", "day": "June 6"}, {"holiday": "National Running Day", "day": "June 7"}, {"holiday": "VCR Day", "day": "June 7"}, 
	{"holiday": "Best Friends Day", "day": "June 8"}, {"holiday": "Donald Duck Day", "day": "June 9"}, {"holiday": "Iced Tea Day", "day": "June 10"}, 
	{"holiday": "Corn on the Cob Day", "day": "June 11"}, {"holiday": "Red Rose Day", "day": "June 12"}, {"holiday": "International Axe Throwing Day", "day": "June 13"}, 
	{"holiday": "Sewing Machine Day", "day": "June 13"}, {"holiday": "Bourbon Day", "day": "June 14"}, {"holiday": "Nature Photography Day", "day": "June 15"}, 
	{"holiday": "Bloomsday", "day": "June 16"}, {"holiday": "World Juggling Day", "day": "June 17"}, {"holiday": "Eat Your Vegetables Day", "day": "June 17"}, 
	{"holiday": "International Picnic Day", "day": "June 18"}, {"holiday": "International Panic Day", "day": "June 18"}, {"holiday": "Sauntering Day", "day": "June 19"}, 
	{"holiday": "National Selfie Day", "day": "June 21"}, {"holiday": "Daylight Appreciation Day", "day": "June 21"}, {"holiday": "Onion Ring Day", "day": "June 22"}, 
	{"holiday": "Take Your Dog to Work Day", "day": "June 23"}, {"holiday": "Typewriter Day", "day": "June 23"}, {"holiday": "National Pink Day", "day": "June 23"}, 
	{"holiday": "Swim a Lap Day", "day": "June 24"}, {"holiday": "Please Take my Children to Work Day", "day": "June 25"}, {"holiday": "Chocolate Pudding Day", "day": "June 26"}, 
	{"holiday": "Helen Keller Day", "day": "June 27"}, {"holiday": "Christopher Street Day", "day": "June 28"}, {"holiday": "Tau Day", "day": "June 28"}, {"holiday": "Camera Day", "day": "June 29"}, 
	{"holiday": "Meteor Watch Day", "day": "June 30"}, {"holiday": "International Joke Day", "day": "July 1"}, {"holiday": "World UFO Day", "day": "July 2"}, 
	{"holiday": "I Forgot Day", "day": "July 2"}, {"holiday": "International Plastic Bag Free Day", "day": "July 3"}, {"holiday": "Compliment Your Mirror Day", "day": "July 3"}, 
	{"holiday": "Sidewalk Egg Frying Day", "day": "July 4"}, {"holiday": "Workaholics Day", "day": "July 5"}, {"holiday": "National Fried Chicken Day", "day": "July 6"}, 
	{"holiday": "World Kissing Day", "day": "July 6"}, {"holiday": "Tell the Truth Day", "day": "July 7"}, {"holiday": "Video Games Day", "day": "July 8"}, {"holiday": "Math 2.0 Day", "day": "July 8"}, 
	{"holiday": "Sugar Cookie Day", "day": "July 9"}, {"holiday": "Teddy Bears' Picnic Day", "day": "July 10"}, {"holiday": "Clerihew Day", "day": "July 10"}, 
	{"holiday": "Cheer Up the Lonely Day", "day": "July 11"}, {"holiday": "Simplicity Day", "day": "July 12"}, 
	{"holiday": "National French Fry Day", "day": "July 13"}, {"holiday": "Embrace Your Geekness Day", "day": "July 13"}, 
	{"holiday": "International Nude Day", "day": "July 14"}, {"holiday": "Pandemonium Day", "day": "July 14"}, {"holiday": "Gummi Worm Day", "day": "July 15"}, 
	{"holiday": "National Ice Cream Day", "day": "July 16"}, {"holiday": "Corn Fritters Day", "day": "July 16"}, {"holiday": "World Emoji Day", "day": "July 17"}, 
	{"holiday": "Yellow Pig Day", "day": "July 17"}, {"holiday": "Caviar Day", "day": "July 18"}, {"holiday": "Stick Out Your Tongue Day", "day": "July 19"}, 
	{"holiday": "National Hot Dog Day", "day": "July 19"}, {"holiday": "Space Exploration Day", "day": "July 20"}, {"holiday": "Junk Food Day", "day": "July 21"}, 
	{"holiday": "Pi Approximation Day", "day": "July 22"}, {"holiday": "Vanilla Ice Cream Day", "day": "July 23"}, {"holiday": "Cousins Day", "day": "July 24"}, 
	{"holiday": "National Tequila Day", "day": "July 24"}, {"holiday": "Culinarians Day", "day": "July 25"}, {"holiday": "Uncle and Aunt Day", "day": "July 26"}, 
	{"holiday": "Take your Pants for a Walk Day", "day": "July 27"}, {"holiday": "Milk Chocolate Day", "day": "July 28"}, {"holiday": "National Chicken Wing Day", "day": "July 29"}, 
	{"holiday": "Lasagna Day", "day": "July 29"}, {"holiday": "National Dance Day", "day": "July 29"}, {"holiday": "National Cheesecake Day", "day": "July 30"}, {"holiday": "National Mutt Day", "day": "July 31"}, {"holiday": "Uncommon Musical Instrument Day", "day": "July 31"}, {"holiday": "Girlfriend's Day", "day": "August 1"}, {"holiday": "Yorkshire Day", "day": "August 1"}, 
	{"holiday": "Ice Cream Sandwich Day", "day": "August 2"}, {"holiday": "Watermelon Day", "day": "August 3"}, {"holiday": "Single Working Women's Day", "day": "August 4"}, 
	{"holiday": "International Beer Day", "day": "August 4"}, {"holiday": "Work Like a Dog Day", "day": "August 5"}, {"holiday": "Fresh Breath Day", "day": "August 6"}, 
	{"holiday": "Sisters' Day", "day": "August 6"}, {"holiday": "Lighthouse Day", "day": "August 7"}, {"holiday": "Happiness Happens Day", "day": "August 8"}, 
	{"holiday": "International Cat Day", "day": "August 8"}, {"holiday": "Book Lovers Day", "day": "August 9"}, {"holiday": "National S'mores Day", "day": "August 10"}, 
	{"holiday": "Lazy Day", "day": "August 10"}, {"holiday": "Son and Daughter Day", "day": "August 11"}, {"holiday": "Middle Child Day", "day": "August 12"}, 
	{"holiday": "Left-Handers Day", "day": "August 13"}, {"holiday": "Creamsicle Day", "day": "August 14"}, {"holiday": "Pythagorean Theorem Day", "day": "August 15"}, 
	{"holiday": "Relaxation Day", "day": "August 15"}, {"holiday": "Tell a Joke Day", "day": "August 16"}, {"holiday": "National Rum Day", "day": "August 16"}, 
	{"holiday": "Thrift Shop Day", "day": "August 17"}, {"holiday": "Mail Order Catalog Day", "day": "August 18"}, {"holiday": "World Photo Day", "day": "August 19"}, 
	{"holiday": "Chocolate Pecan Pie Day", "day": "August 20"}, {"holiday": "Spumoni Day", "day": "August 21"}, {"holiday": "Be An Angel Day", "day": "August 22"}, 
	{"holiday": "Ride Like the Wind Day", "day": "August 23"}, {"holiday": "National Waffle Day", "day": "August 24"}, {"holiday": "Pluto Demoted Day", "day": "August 24"}, 
	{"holiday": "Kiss and Make up Day", "day": "August 25"}, {"holiday": "National Dog Day", "day": "August 26"}, {"holiday": "Dog Appreciation Day", "day": "August 26"}, 
	{"holiday": "The Duchess Who Wasn't Day", "day": "August 27"}, {"holiday": "Bow Tie Day", "day": "August 28"}, {"holiday": "According to Hoyle Day", "day": "August 29"}, 
	{"holiday": "Frankenstein Day", "day": "August 30"}, {"holiday": "Eat Outside Day", "day": "August 31"}, {"holiday": "No Rhyme or Reason Day", "day": "September 1"}, 
	{"holiday": "Emma Nutt Day", "day": "September 1"}, {"holiday": "Bison Ten Yell Day", "day": "September 2"}, {"holiday": "Skyscraper Day", "day": "September 3"}, 
	{"holiday": "Eat an Extra Dessert Day", "day": "September 4"}, {"holiday": "Cheese Pizza Day", "day": "September 5"}, {"holiday": "Be Late for Something Day", "day": "September 5"}, 
	{"holiday": "Read a Book Day", "day": "September 6"}, {"holiday": "Fight Procrastination Day", "day": "September 6"}, {"holiday": "Salami Day", "day": "September 7"}, 
	{"holiday": "Pardon Day", "day": "September 8"}, {"holiday": "Teddy Bear Day", "day": "September 9"}, {"holiday": "Swap Ideas Day", "day": "September 10"}, 
	{"holiday": "Make Your Bed Day", "day": "September 11"}, {"holiday": "National Video Game Day", "day": "September 12"}, {"holiday": "Chocolate Milkshake Day", "day": "September 12"}, 
	{"holiday": "Roald Dahl Day", "day": "September 13"}, {"holiday": "Positive Thinking Day", "day": "September 13"}, {"holiday": "Hug Your Hound Day", "day": "September 14"}, 
	{"holiday": "International Dot Day", "day": "September 15"}, {"holiday": "Make a Hat Day", "day": "September 15"}, {"holiday": "Guacamole Day", "day": "September 16"}, 
	{"holiday": "Collect Rocks Day", "day": "September 16"}, {"holiday": "International Country Music Day", "day": "September 17"}, {"holiday": "Wife Appreciation Day", "day": "September 17"}, 
	{"holiday": "Rice Krispie Treat Day", "day": "September 18"}, {"holiday": "National Cheeseburger Day", "day": "September 18"}, {"holiday": "National Gymnastics Day", "day": "September 19"}, 
	{"holiday": "International Talk Like a Pirate Day", "day": "September 19"}, {"holiday": "Punch Day", "day": "September 20"}, {"holiday": "Miniature Golf Day", "day": "September 21"}, 
	{"holiday": "Mabon", "day": "September 22"}, {"holiday": "Hobbit Day", "day": "September 22"}, {"holiday": "Checkers Day", "day": "September 23"}, {"holiday": "Punctuation Day", "day": "September 24"}, 
	{"holiday": "Comic Book Day", "day": "September 25"}, {"holiday": "Love Note Day", "day": "September 26"}, {"holiday": "Johnny Appleseed Day", "day": "September 26"}, 
	{"holiday": "Crush a Can Day", "day": "September 27"}, {"holiday": "National Drink Beer Day", "day": "September 28"}, {"holiday": "Ask a Stupid Question Day", "day": "September 28"}, 
	{"holiday": "Good Neighbor Day", "day": "September 28"}, {"holiday": "National Coffee Day", "day": "September 29"}, {"holiday": "Astronomy Day", "day": "September 30"}, 
	{"holiday": "Hot Mulled Cider Day", "day": "September 30"}, {"holiday": "National Public Lands Day", "day": "September 30"}, {"holiday": "International Coffee Day", "day": "October 1"}, 
	{"holiday": "Balloons Around the World Day", "day": "October 1"}, {"holiday": "Phileas Fogg Wager Day", "day": "October 2"}, {"holiday": "National Boyfriend Day", "day": "October 3"}, 
	{"holiday": "World Animal Day", "day": "October 4"}, {"holiday": "National Vodka Day", "day": "October 4"}, {"holiday": "Taco Day", "day": "October 4"}, {"holiday": "Chic Spy Day", "day": "October 5"}, 
	{"holiday": "World Smile Day", "day": "October 6"}, {"holiday": "Mad Hatter Day", "day": "October 6"}, {"holiday": "Frapp\u00e9 Day", "day": "October 7"}, {"holiday": "Card Making Day", "day": "October 7"}, 
	{"holiday": "Pastor Appreciation Day", "day": "October 8"}, {"holiday": "Pierogi Day", "day": "October 8"}, {"holiday": "Curious Events Day", "day": "October 9"}, 
	{"holiday": "Handbag Day", "day": "October 10"}, {"holiday": "It's My Party Day", "day": "October 11"}, {"holiday": "National Coming Out Day", "day": "October 11"}, 
	{"holiday": "Old Farmers Day", "day": "October 12"}, {"holiday": "International Skeptics Day", "day": "October 13"}, {"holiday": "National No Bra Day", "day": "October 13"}, 
	{"holiday": "National Dessert Day", "day": "October 14"}, {"holiday": "I Love Lucy Day", "day": "October 15"}, {"holiday": "National Clean Out Your Virtual Desktop Day", "day": "October 16"}, 
	{"holiday": "Dictionary Day", "day": "October 16"}, {"holiday": "Wear Something Gaudy Day", "day": "October 17"}, {"holiday": "National Pasta Day", "day": "October 17"}, 
	{"holiday": "Chocolate Cupcake Day", "day": "October 18"}, {"holiday": "International Sloth Day", "day": "October 20"}, {"holiday": "Count your Buttons Day", "day": "October 21"}, 
	{"holiday": "Sweetest Day", "day": "October 21"}, {"holiday": "Apple Day", "day": "October 21"}, {"holiday": "National Nut Day", "day": "October 22"}, {"holiday": "Caps Lock Day", "day": "October 22"}, 
	{"holiday": "Mole Day", "day": "October 23"}, {"holiday": "Bologna Day", "day": "October 24"}, {"holiday": "Sourest Day", "day": "October 25"}, 
	{"holiday": "Howl at the Moon Day and Night", "day": "October 26"}, {"holiday": "National Pumpkin Day", "day": "October 26"}, {"holiday": "American Beer Day", "day": "October 27"}, 
	{"holiday": "National Black Cat Day", "day": "October 27"}, {"holiday": "National Chocolate Day", "day": "October 28"}, {"holiday": "International Observe the Moon Night", "day": "October 28"}, 
	{"holiday": "International Animation Day", "day": "October 28"}, {"holiday": "Make a Difference Day", "day": "October 28"}, {"holiday": "National Cat Day", "day": "October 29"}, 
	{"holiday": "Internet Day", "day": "October 29"}, {"holiday": "Candy Corn Day", "day": "October 30"}, {"holiday": "Magic Day", "day": "October 31"}, {"holiday": "Author's Day", "day": "November 1"}, 
	{"holiday": "Men Make Dinner Day", "day": "November 2"}, {"holiday": "Deviled Eggs Day", "day": "November 2"}, {"holiday": "Sandwich Day", "day": "November 3"}, 
	{"holiday": "Common Sense Day", "day": "November 4"}, {"holiday": "Zero Tasking Day", "day": "November 5"}, {"holiday": "Saxophone Day", "day": "November 6"}, 
	{"holiday": "Bittersweet Chocolate with Almonds Day", "day": "November 7"}, {"holiday": "Tongue Twister Day", "day": "November 8"}, {"holiday": "Chaos Never Dies Day", "day": "November 9"}, 
	{"holiday": "Forget Me Not Day", "day": "November 10"}, {"holiday": "Vanilla Cupcake Day", "day": "November 10"}, {"holiday": "Origami Day", "day": "November 11"}, 
	{"holiday": "Happy Hour Day", "day": "November 12"}, {"holiday": "World Kindness Day", "day": "November 13"}, {"holiday": "Sadie Hawkins Day", "day": "November 13"}, 
	{"holiday": "Pickle Day", "day": "November 14"}, {"holiday": "Spicy Guacamole Day", "day": "November 14"}, {"holiday": "America Recycles Day", "day": "November 15"}, 
	{"holiday": "Clean Out Your Refrigerator Day", "day": "November 15"}, {"holiday": "Use Less Stuff Day", "day": "November 16"}, {"holiday": "Fast Food Day", "day": "November 16"}, 
	{"holiday": "Take A Hike Day", "day": "November 17"}, {"holiday": "National Adoption Day", "day": "November 18"}, {"holiday": "Mickey Mouse Birthday", "day": "November 18"}, 
	{"holiday": "Push Button Phone Day", "day": "November 18"}, {"holiday": "National Absurdity Day", "day": "November 20"}, {"holiday": "World Hello Day", "day": "November 21"}, 
	{"holiday": "Go For a Ride Day", "day": "November 22"}, {"holiday": "Fibonacci Day", "day": "November 23"}, {"holiday": "National Day of Mourning", "day": "November 23"}, 
	{"holiday": "Celebrate Your Unique Talent Day", "day": "November 24"}, {"holiday": "Buy Nothing Day", "day": "November 24"}, {"holiday": "Shopping Reminder Day", "day": "November 25"}, 
	{"holiday": "Cake Day", "day": "November 26"}, {"holiday": "Red Planet Day", "day": "November 28"}, {"holiday": "Electronic Greeting Card Day", "day": "November 29"}, 
	{"holiday": "Computer Security Day", "day": "November 30"}, {"holiday": "Eat a Red Apple Day", "day": "December 1"}, {"holiday": "National Mutt Day", "day": "December 2"}, 
	{"holiday": "Fritters Day", "day": "December 2"}, {"holiday": "Make a Gift Day", "day": "December 3"}, {"holiday": "National Cookie Day", "day": "December 4"}, 
	{"holiday": "Wear Brown Shoes Day", "day": "December 4"}, {"holiday": "Day of the Ninja", "day": "December 5"}, {"holiday": "Put on Your Own Shoes Day", "day": "December 6"}, 
	{"holiday": "Microwave Oven Day", "day": "December 6"}, {"holiday": "Letter Writing Day", "day": "December 7"}, {"holiday": "National Brownie Day", "day": "December 8"}, 
	{"holiday": "Official Lost and Found Day", "day": "December 8"}, {"holiday": "Pretend to Be a Time Traveler Day", "day": "December 8"}, {"holiday": "Christmas Card Day", "day": "December 9"}, 
	{"holiday": "Jane Addams Day", "day": "December 10"}, {"holiday": "Dewey Decimal System Day", "day": "December 10"}, {"holiday": "Noodle Ring Day", "day": "December 11"}, 
	{"holiday": "Gingerbread House Day", "day": "December 12"}, {"holiday": "Christmas Jumper Day", "day": "December 13"}, {"holiday": "Monkey Day", "day": "December 14"}, 
	{"holiday": "National Cupcake Day", "day": "December 15"}, {"holiday": "Chocolate Covered Anything Day", "day": "December 16"}, {"holiday": "Free Shipping Day", "day": "December 16"}, 
	{"holiday": "Wright Brothers Day", "day": "December 17"}, {"holiday": "Underdog Day", "day": "December 19"}, {"holiday": "Ugly Sweater Day", "day": "December 19"}, 
	{"holiday": "Sangria Day", "day": "December 20"}, {"holiday": "International Dalek Remembrance Day", "day": "December 21"}, {"holiday": "Yule", "day": "December 21"}, 
	{"holiday": "Date Nut Bread Day", "day": "December 22"}, {"holiday": "Festivus", "day": "December 23"}, {"holiday": "Eggnog Day", "day": "December 24"}, 
	{"holiday": "Grav Mass Day", "day": "December 25"}, {"holiday": "A'phabet Day or No &quot;L&quot; Day", "day": "December 25"}, {"holiday": "Thank You Note Day", "day": "December 26"}, 
	{"holiday": "No Interruptions Day", "day": "December 27"}, {"holiday": "Card Playing Day", "day": "December 28"}, {"holiday": "Pepper Pot Day", "day": "December 29"}, 
	{"holiday": "Bicarbonate of Soda Day", "day": "December 30"}, {"holiday": "National Bacon Day", "day": "December 30"}, {"holiday": "Make Up Your Mind Day", "day": "December 31"}
	]

absurds = ["pickles","butts","oranges","falling","greenbacks","jupiter","sand","in a tizzy","gone","a black hole"]

nicknames = ["wee couch potato","my filthy child","meat sack","my living sponge","wee blood bag","my pizza muncher","my good bitch","shiny boi",
	"old friend","total stranger","soft stranger","chosen one","my dearest","darling","sweetheart,my dove","poppet","kitten",
	"my turtle","my turtle dove","my lamb","my duckling","honeysuckle","honey","my lovely","my cabbage","pumpkin","sugar",
	"my brown eyed girl","beautiful","gorgeous","my prince","my princess","my love","my nemesis","lover boy","my dear",
	"my darling","little poppet","poppet","babe","baby-face","my child","my beard","babykins","bird","blossom","you cute little button you",
	"charming human","human","cherub","cocksman","cowboy","crumpet","cuddle-bear","cupcake","daddy","dear-one","dearie",
	"dollface","my dream","you breatboat","my fellow","my good fellow","girl","boy","glitterbug","gumdrop","hun","mommy",
	"you heartthrob","hot stuff","my knight in shining armour","you knockout","my little dove","main squeeze","muggle","old man",
	"old woman","peach","pet","my pet","my little pet","puppy","my precious","puddin'","my spark","my squire","sunshine","sweetheart",
	"sweetie"

	]

tasks = ["buy 1000 USB sticks","troll someone with Allstar","eat a bagel","call your boss and ask for a raise",
	"write a letter to your representative","call your representative","take a walk around the block","forgive yourself",
	"go rock climbing","take a friend out for coffee","call your mum","call your mother","call your dad","call your father",
	"walk along the beach","cover your body in hot wax","go bird watching","attempt to swallow the Don River whole",
	"find a dog and explain string theory to them","pick flowers","go to Allen Gardens",
	"rearrange cobblestones in the Distillery District","talk to a stranger at a bar you’ve never been to",
	"sing a ballad in Dufferin Mall","complement a bus driver","bake a loaf of bread",
	"bake a loaf of bread in Dufferin Grove Park","collect dirt from a place you’ve never been","build a miniature log cabin",
	"take a deep breath and release the tension from your shoulders","clear out your email",
	"login to your first email","login to your old Neopet’s account","use a map of another city to explore yours",
	"walk without purpose west until you have no idea where you are anymore","scream into the void",
	"go to the dentist and see if they’ll give you any old teeth","give away something important to you but don’t need",
	"collect fallen leaves and keep them for your records - or at least put them in the box you put your taxes in",
	"darn a hole in your clothing","sew something - anything","find time for yourself and recall your favourite memory - feel it in your bones and fill you with joy",
	"break something","go down to the Leslie St Spit and build something out of the garbage at the lighthouse",
	"buy flowers and clean the gravestone of someone you’ve lost","buy flowers and clean the gravestone of someone you’ve never met",
	"go out to the bar alone - you deserve the silence","drink your spirit of choice with an old friend in a public park",
	"buy new socks - your old ones have too many holes","buy someone else a pack of socks - you’ve noticed the holes in all of theirs",
	"make an offering the the Old Gods of the city - the ones smothered by concrete and sewage piping",
	"collect the snow melt water in the spring - it’s good for your plants","disappear for a few days to recharge",
	"ride the TTC to the end of the line both ways","see how far you can get only taking alleyways",
	"collect flowers and press them in a book","connect with a childhood friend you haven’t spoken to in years",
	"go somewhere you feel very tiny and marvel at the immense size of the universe","cuddle up under warm blankets and watch your favourite childhood movie",
	"take a hike","make your favourite warm drink and listen to recordings of rain fall",
	"let go of something that hurt you","volunteer with Food Not Bombs","try knitting something",
	"get a plant and see how long you can keep it alive","feed seagulls at the beach",
	"call your grandmother - or someone who is important to you","call your grandfather - or someone who is important to you",
	"throw out the things you’re still holding onto from your last breakup","run away for a few days and take some time to be alone",
	"go to a quarry","try whittling something","go down to the train tracks and watch the trains go","write with an ink and quill pen",
	"go to a steam room - there’s a good one in North York","try alchemy","find a hole in a mountain the perfect size for you",
	"walk outside in the next storm and feel nature-know that you are small","try blacksmithing","get a tattoo","learn to trust again",
	"cut a lock of your hair and mail it to an unknown address","make yourself a pillow fort in your apartment","reread your favourite book",
	"buy as many bouncy balls as you can and see how many you can bounce at one time","make a new friend","go to a meetup you’ve always wanted to go to but felt intimidated",
	"put yourself out there - you deserve happiness","keep all your toenail clippings for a year","keep your promise",
	"be silent for a day","paint in blue","go to a animal sanctuary and look at the cute animals",
	"sit by a fireside","take time to stretch today - feel yourself relax","take time to organize your personal space",
	"go to your old high school haunts - think of how much you’ve grown as a person","walk in the forest in barefeet",
	"make a hot toddy","drive out east to the sea and breath in the salty air","try sailing",
	"write about your day and burn the paper - sometimes it is better to forget","seek comfort in your friends",
	"go to a pet store and look at the salamanders - we once believed they came from the embers of fires",
	"take time to appreciate your daily rituals - they make you who you are","restock your first aid kit - you have one don’t you?","make a musical house",
	"wander around a bookstore until you find something that interests you","try edible flowers",
	"go through all your pens and check which ones work","take a walk around the neighbourhood and look at all the different windows",
	"try growing sprouts","relax in a hammock","listen to the trees’ stories","watch the sunset","watch the sunrise",
	"buy a nice aftershave","cook something new","explore North York","try cross stitching",
	"hang out with a baby","go paintballing","get fucked up","organize a community dinner","drink a bottle of wine to yourself","smash a vase",
	"fight a badger","have a really really good cry","go hiking in the winter","watch a children’s show",
	"get lost","take the first steps to completing your dreams","make sweet lemonade","try eating organ meat",
	"make stew","shave all the hair off your body and cover yourself in lube to slip around on a tarp",
	"listen to the same music you listened to in high school to take a trip down memory lane",
	"sit in complete darkness and listen to your body","make mud pies","stand in the lake",
	"wade into the lake somberly","go to the opera","throw a house party","listen to sandstorm on repeat",
	"knit a scarf","clip interesting stories out of the newspaper and try and connect the stories with string",
	"sleep in","give flowers to a friend","make the spiciest curry you can stand","take a photograph everyday for a week",
	"buy caterpillars from a petstore and take care of them until they hatch into butterflies",
	"empty the trash already - it stinks","go to Montreal and rock out at a punk show","fix the holes in the walls",
	"sew your lips shut","leave out offerings for the birds - the more elaborate the better","learn how to solder",
	"be part of the resistance","overthrow capitalism","go mushroom picking","go to Dufferin Park and have a fire in one of the pits",
	"change careers","get in a drunken fight","get a magnetic implant in your finger","replace your limbs with cybernetics",
	"make a promise you intend to keep","make a promise you never intend to keep","take a nap",
	"walk around Value Village and find something that means something to you",
	"tell only lies for the rest of the day","write down the next dream you have",
	"mix drinks that are inspired by your memories","make a paintbrush out of your own hair and paint something",
	"be truthful","finish a notebook or sketchbook","move out of your apartment","make ginger tea","get a massage",
	"try some autoerotic asphyxiation next time you masterbate","prank call someone","go to the ocean",
	"make a card and give it to someone you love","try stinging nettle tea","return to a place you find painful and forgive yourself",
	"get the flu shot","try shooting a gun at a gun range","make friends with a bartender","try contouring next time you put on makeup",
	"clean the bathroom","bake cookies","make stock from scratch","build something with your hands","try to make stained glass",
	"go to the ROM","go to the AGO","go to a gallery opening and make friends with the artist","fly south for the winter",
	"lay down and wait until death takes you","try and make a black hole in your basement","walk into the valley",
	"make a witch’s broom","burn your memories","give in","give up","fight until your body gives out",
	"ride the streetcar to the end both ways","delete your Facebook","go to the desert",
	"scream into the void until your lungs give out and you’re shaking and crying",
	"find kinship in the strangest places","dance with your pants off","give money away to someone in need if you can",
	"watch the Matrix","grow tomatoes","pet a cat","get a new toothbrush - when was the last time you went to the dentist",
	"draw on grid paper","try sketching","steal a stop sign",
	"leave small amounts of money in your friends coats and watch their eyes light up when they find it",
	"fix the broken zipper on your coat","draw with a sharpie","draw in the street with chalk",
	"steal a rail spike from the train tracks","put all your clothes on hangers","do your laundry",
	"make your bed","try making a stop motion short","play some video games","find a tire swing and pretend you’re a kid again",
	"learn American Sign Language","clean your fridge","play pool at a bar in the east end",
	"get a blacklight and have a glow stick party - highlighter lights up under black light too","play twister"
	]

verbs = ["accept","acknowledge","attack","approach","attain","be","beat up","bring with you","become","begin","bend","bet","bid on",
	"bite down onto","blow a balloon with the image of","break","bring","build","burn","buy","catch","choose","contact","cut",
	"dig","dice","do","draw","dream of","drive to","eat","feel relieved about","fight","find","forgive","freeze","get","give","go to","hang",
	"hear a","hear of","hide","hit","hold","hurt","keep","know","lay on","lay hands on","lead","let in","let go of","lie to","lose against",
	"make amends with","meet","read","ride","ring a bell calling","run a race against","say","see","sell","send","show",
	"sing to","sit upon","spend way too much money on","stand uncomfortably close to","swim across the lake to reach",
	"barrel angrily towards","anxiously approach","reach out to","bend over backwards to accommodate","reach deep into the depths of your soul to find",
	"stumble","trip","take","tear","tell","throw","wake","wear","win","write","acquire","reach out to","sink your teeth into","scratch","sharpen","trail","strip","wrend",
	"stalk","stitch","peel","drag your rotten corpse to","approach with the utmost confidence","accidentally brush your hand against","program","prance merrily to","invent",
	"shit out","cautiously approach","sip tea with","slit the throat of","give CPR (I hope you’ve been practicing!) to","switch on","be kept in the dark by","climb",
	"fuck around with","spend your last dollar on","give all your worldly possessions to","breath life into the cold dead body of","sing your siren song to",
	"eat every last earthly morsel of","take illicit drugs with","stitch the flesh of the dead to create","find a baseball bat decorated with","eviscerate",
	"clutch your pearls as you’re confronted by","fall in love","fall in hate with","find the perfect nemesis in","wreck","walk into your basement apartment to find",
	"cry on the shoulder of","reach out in desperation to","sob into the loving chest of","break dance with",
	"fight with every last breath inside your tiny human body to get to","sing with the glory of the universe to",
	"feel the hands of death clutch your throat as","drunkenly run into","embarrass yourself infront of",
	"lust unrequitedly after","choke out","choke on","sleep with","find yourself fucking","lead an unruly mule to",
	"acknowledge the unrelenting universal force of","ravage the eternal existence of","find the root of all existence through","barrel head long into",
	"ponder the impossibility of","cry in horror at the sudden and unavoidable truth that you cannot comprehend","apologies for stumbling upon","sit down and have a very positive heart to heart with a",
	"organize a parade in honor of","devote your life to the worship of","fall deep into a self perpetuating cycle of hunger only interrupted by feverish dreams of",
	"reclaim","make amends with","listen to","crack open","step on","curb stomp","tickle","touch gently","annoy","be reminded of",
	"sit down and have a heart to heart with","think about","alight","awaken","bear the sight of","beseech","be told to do the bidding of","bind to your soul",
	"bleed","blend","break the will of","cast the shape of","clothe","dwell upon","feed","forsake","heave","hurt","kneel in front of","lie to",
	"pay a large sum of money to","read about","seek the advice of","shear","shoot dirty looks at","shrink away from","sleep next to",
	"smite","spill milk on","stand next to","steal from","strive to best","take","take a swing at","teach","wake up","weave into tapestry","write about","mourn","call your representative about"
	]


objects = ["a dog","a horse","a cat","a former lover","a current lover","your best friend","a lonely stranger","your mother","your father","your sister","your brother",
	"your boss","a stranger","a creature made of mist","the angriest hedgehog you’ve ever seen","the concept of the universe itself","a swamp thing","the first moment you knew yourself","a roach",
	"a formless mass","a wandering storyteller","a fiddler","a siren","a werewolf","a witch","a cow named Bessy (the unoriginal fuck)",
	"the creeping sense of embarrassment that everyone knows something about you but you can’t quite place what it is","a goffer","the person you first told your deepest secret to",
	"the concept of dreams","the unknowable","a metal cover band","the sharpest nail in the box","a screamo band","a ska band",
	"the person who has basically the same schedule as you so you see them at the bus stop all the time","the ever encroaching hand of Facebook",
	"that same punk kid you see at all the shows you used to go to sitting in a coffee shop","the person you hurt the most","a literal dumpster fire",
	"the friend you lost contact with due to time and circumstance","an ice storm","the person whose life you altered for the better","the person you left with things unsaid to",
	"a whirlwind","a monster made of your greatest fears","the fading sense of control you have on your life","an ascensor","a white bear speaking tongues","a trash panda",
	"a raccoon sitting at your window too scared to go up or down your neighbour’s drainpipe","a first date","Beyonce","a creeping sense of unattainable joy",
	"the person you imagined yourself you’d become when you were 9","a talking horse head","a human skull from the dollar store","a comic book from the local shop",
	"the man from the corner store","the weird kid who dresses up as Spiderman and hangs fake webs everywhere","your childhood pet","the chickens you hatched in kindergarten",
	"a hangnail","all of the unanswered emails sitting in your inbox","a goth","a scene kid straight out of 2007","your grandmother","your grandfather","the person who you admire most",
	"all known human knowledge","that guy you fucked when you were 19 and didn’t know better","the girl you kissed in middle school","that woman sitting across from you on the Yonge Line",
	"the guy who plays music on his phone on the TTC","a literal train","Guillermo del Toro","your middle school math teacher","the priest who told you to consider sunday school for suggesting abortions were ok",
	"an arsonist","a toddler","a pounding headache","a gentle touch from a stranger","pervasive toxic masculinity","a Facebook event you’re interested in but will never go to","a baby koala",
	"tuning into a conversation at an inopportune time","12 rabbits speaking in unison in your mother’s voice","a very disgruntled cat dress as a wizard",
	"a detailed blueprint of the room you first thought of your own mortality in","those leftovers you kept saying you were going to eat for lunch until it grew so much mold developed sentience and you were forced to kill it","the vague memory of your favourite meal",
	"that asshole who always brings his friend to your apartment without asking","a squirrel suddenly stopped in the middle the road and can’t make up it’s mind where it should go",
	"an uncomfortably passive aggressive facebook post vaguely directed at you","the broken ipod in your drawer","a single shoelace","a ball of twine",
	"the CD case that held your prized collection before you got an iPod","a mouldy peach","The Mouldy Peaches","the box of stuff you keep moving with but never unpack",
	"the pile of things you mean to return to people but never get around to","several chicken bones","52 jokers","an incredibly expensive bottle of olive oil","a 3D printed yoda head",
	"your jar full of depleted batteries","Bart Simpson","an old man offering you a sword","a couch which may of may not have bedbugs","a single screw","the best game of pinball you’ve ever played",
	"someone you thought you’d never see again","the boundlessness of the eternal void","entirely formless fear","literal garbage","the inevitable heat death of the universe",
	"the reaching hand of Satan","the answer to life the universe and everything","happiness","being forever at arm’s length","an Internet of Things thing",
	"a rabid dog watching you from your peripheral vision","a tall stranger wearing loafers","a cursed sewing machine","a tourist","a cold one with the boys",
	"a counter counting down an explosion to the experimental lab you’ve been trapped in","a sexual encounter with a gentle stranger","a fight to the death","a quick game of tic tac toe",
	"someone who pronounces it ‘jif’","a room full of candle wax","a man attempting to swallow a river","a woman attempting to get a chicken bone out of her dog’s mouth","fiddleheads",
	"a cobblestone from the French Revolution","a piece of the Berlin Wall","a vial filled with dirt from an unknown location","a vial filled with fresh blood",
	"a jar filled with the dying breath of a stranger apparently","a credit card that isn’t yours lodged between your couch cushions","a warm cup of tea","human teeth",
	"a bucket of old paint","a childhood memento","six sewing needles","a ketchup packet","a mickey of Fireball","a stake from the train tracks","a trip to the bar alone",
	"a chip of your gravestone handed to you by a time traveller claiming to be your descendant","an old pair of socks","a lock of human hair","a mason jar of apparently glacier water",
	"a handful of cranberries","a crumple transfer from the Queen streetcar","a swift kick under the table as you fall asleep in an important meeting","a yellow leaf","an aloe plant",
	"a bag of Earl Grey tea","a handknit sweater","a handful of pink yarn","just some dirt","a hot bowl of soup from Food Not Bombs",
	"a shirt your ex left behind but it’s been too long to give back without it getting weird","a really old looking pigeon","a handwritten letter from your grandmother","a couple of stones","a pack of matches",
	"a pack of matches which started a house fire","a bunch of wood shavings","a whittled toy sword","what appears to be a sack of runes","a vial of ink","an old quill","a break from your worries","a literal mountain",
	"a metaphorical mountain","a bunch of iron shaving","the needles you got your first tattoo with","a bag full of your toenail clippings","one of those CPR practice dummies","a good book",
	"an old book that’s missing its front cover","a blanket fort","a bouncy ball","a shard of glass","a piece of ice from the back of the freezer","a broken promise","one of those friendship necklaces from Claire’s",
	"the worn out shoes of your father","an owlet","a contract outlining the inheritance of a debt consisting of twelve seagulls and a chop saw","a chop saw","one of those pink salt lamps",
	"a sailboat","a piece of driftwood","a Motorola Razr phone in pink","a used needle","a salamander","everything you’d need for a human sacrifice","a mousetrap","an edible flower","a stone heart",
	"an artificial heart","a broken window","a first aid kit","a hammock","a half full can of spray paint","a snake skin","a glass skull","a taxidermied duck","a birch sapling","a rock climbing harness",
	"a half used bottle of aftershave","an old woman of the woods","horse teeth","fresh blueberries from up north","a single strawberry","a new frying pan","whatever is behind door number 7",
	"a lunch of charcoal","a newborn baby","a ferret","a deer","a stag","a fox","a wolf","an eagle","an orchid","a bottle of red wine","a fish hook","an old grandfather clock","a SAD lamp",
	"a fresh pack of cigarettes","an empty pack of cigarettes","a vase","a pack of bandaids","an industrial bottle of lube","a single badger claw","a vial of tears shed in sadness",
	"a stone from the centre of the forest","a selkie","a single use hand warmer pack","a sweet lemon","a start-up company founded on the concept of free labour","the death rattle of capitalism",
	"organ meat","a stretched out binder","the scent of juniper","a bottle of cheap gin","a clock set fifteen minutes too fast","the concept of darkness","seawater in a plastic bag","a skinwalker",
	"a gift from an old friend","an unmarked package","a package seemingly from another time","a violin","the song sandstorm on cassette tape","a windmill","a scarf from a tourist shop","a handknit scarf",
	"a sleeping bag","a package of printer paper","your high school transcript","your second grade report card","all the hair ties you lost behind the couch","the change between the couch cushions",
	"one of those premixed spice packages","a photographer","a bunch of live mealworms from the local pet shop","the nostalgia you feel for a time you never lived in","the looming stink of the unemptied trash can",
	"stickers","a fucking laser gun","a rooster","Baba Yaga riding in on her cauldron coming to fuck you up","the song your mother sung to you before you knew how to make memories","a lose-lose situation",
	"a single lightbulb swinging in an empty room","a package of mushrooms","an overgrown houseplant","your landlord","the bartender","your last will and testament","bone china","your toothbrush","birdsong",
	"a blue whale","a crow","a rookerie","a piece of ginger","a spool of thread","the first snow","your collection of unfinished notebooks","an old analogue phone","a human heart","a pumpkin pie",
	"a single mouse you can hear in the walls","stinging nettle","your flu shot you keep saying you’ll get","a shot of vodka","a birdcage filled with sparrows","the burnt out house on your block that hasn’t been fixed up in half a decade",
	"a beach filled with garbage","a sunken ship","a black hole","the 504 streetcar","a horseshoe crab","a grease fire","the concept of death","the moment between sunset and twilight",
	"the best day of your life (yet)","sacrificing your first born to the Old Gods","an anteater","moths","that box you never unpack every time you move",
	"a roasted chicken","that feeling of unrequited friendship","a queer crush","a burnt cup of coffee","a youtube video playlist of every episode of How It’s Made"
	]

dates = ["tomorrow","today","later this evening","in a fortnight","on the day you’re scheduled to die (we’re still waiting on the paperwork from your birth",
	"we’ll let you know when it’s in the queue)","on the fall equinox","on the winter equinox","on the spring equinox","on the summer equinox","next week",
	"your next shift at work","sometime in the future","at I dunno I didn’t really check the time","at 15:00 EST","when the sun sets in the east",
	"during the heat death of the universe","the moment you know true tranquility","the next time you drink",
	"when you’re blinded by rage","once you leave this room","the next time you receive a call","when the crows return to the city of Toronto","when you run into an old friend",
	"2864895 heartbeats from now","at the next concert you go to","next time you cross Queen st","next week","next Tuesday","next Monday","next Wednesday","next Thursday","next Friday",
	"next Saturday","next Sunday","next time you enter a car","the next time you ride the TTC","once you finally accept your true self","when you finally send your last desperate text to your ex",
	"half past six","quarter past three","half past eleven","forty minutes into your next meeting","the next time you wake up in the middle of the night",
	"in the half hazy moments when your dreams are still real and reality isn’t","the next time you order an expensive coffee","the next time you settle in for a nap",
	"next time you go out to treat yourself at dinner","the next time you order take-out","once you accept the earth is flat",
	"the next time you watch a YouTube video about something you probably should already know how to do","once you finally download the current version of your operating system",
	"once you’re prepared to forgive yourself","the next time you lash out in anger","the next time you drink too much",
	"the next time you reach out in need","the next time the weather is just right for you","once the weather is cold again","once the weather is hot again",
	"once the moon is full","when the moon is the same as the day you were born","once all the condos are done being built","once the memes run out",
	"the next time you log into your email","once you finally catch up on everything you’ve been meaning to watch",
	"the next time you stare deep into a stranger’s eyes and know that they are unknowable","the next time you are overcome with sadness",
	"the next time you are overcome with happiness","once you finally let go","once you accept mortality"
	]

locations = ["at Yonge and Dundas","at Bloor station","at Spadina station","in Kensington market","in the Annex",
	"just outside your work","at the St. Lawrence Market","walking up Jarvis","at your local bar","at your local convenience store",
	"in the same place you made your biggest regret","lying in the middle of the road","outside the building you always look into on your walk to work",
	"at your old school","inside the Eaton’s Centre","waiting on the tarmac for your next flight to take off","outside of this venue","walking home late at night",
	"in the shortcut through the construction site","deep in Scarborough","on the Go Train","in the Beaches","while walking home late at night","at your friend’s birthday party",
	"standing outside waiting for the bus","Dufferin station","walking by the AGO","taking a shortcut through the park","at home","in your front hallway","in the bathroom",
	"walking down Queen street","in your friends bathroom","in your bathroom","outside your office","in a back alley","snuggled under your covers in bed","in the bath",
	"standing in the shadow of Casa Loma","walking down by the water","on the beach","in the Beaches","in the bathroom at a club","in the entranceway to your home","at your parents house",
	"at Dufferin Mall","next to you at the streetcar stop","at a truck stop","at an OnRoute station though which one I can’t be sure - they all look the same to me","in your childhood home",
	"the fanciest condo on the block","in a 1970’s highrise","in your living room","in your bedroom","at a holiday market","near the AGO","on the roof of your friend’s old apartment","just down the street",
	"outside your old apartment","inside your old apartment-wait did you break in?","at the local hole in the wall","at your elementary school","two seats ahead of you on the streetcar",
	"at the wrong TTC stop","at your high school","down the street from OCAD","on U of T campus",
	"by the ROM","in Northern Ontario","in Peterborough","in Ottawa","at the bus station in Montreal","at a gallery opening",
	"in the walk in freezer of your favourite restaurant", "in a forgotten part of the city", "walking along the Don River", 
	"on the porch of your best friends house"
	]
